### ISSUE TITLE
Post ship blanks as .stp?

### ISSUE THREAD

**Issue by hattonk** [Kariko83/X-wing-Custom-Storage-Bins#1]
I downloaded the ship blanks as .sldprt files to create some of my own trays, but haven't been able to open them with anything. Would it be possible for you to post the files as .stp files?

**Comment by Kariko83** [comment]
I will look into doing this over the weekend.

**Comment by Kariko83** [comment]
I added STEP files fore each of the finished ship blanks

**Comment by hattonk** [comment]
Awesome, thank you!
